/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Enums;

/**
 *
 * @author Jean
 */
public enum Nacionalidad {
    AFGANISTAN, ALBANIA, ALEMANIA, ANDORRA, ANGOLA, ANTIGUA_Y_BARBUDA,
    ARABIA_SAUDITA, ARGELIA, ARGENTINA, ARMENIA, AUSTRALIA, AUSTRIA, AZERBAIYAN,
    BAHAMAS, BANGLADES, BARBADOS, BAREIN, BELGICA, BELICE, BENIN, BIELORRUSIA,
    BIRMANIA, BOLIVIA, BOSNIA_Y_HERZEGOVINA, BOTSUANA, BRASIL, BRUNEI, BULGARIA,
    BURKINA_FASO, BURUNDI, BUTAN, CABO_VERDE, CAMBOYA, CAMERUN, CANADA, CATAR,
    CHAD, CHILE, CHINA, CHIPRE, CIUDAD_DEL_VATICANO, COLOMBIA, COMORAS,
    OREA_DEL_NORTE, COREA_DEL_SUR, COSTA_DE_MARFIL, COSTA_RICA, CROACIA, CUBA,
    DINAMARCA, DOMINICA, ECUADOR, EGIPTO, EL_SALVADOR, EMIRATOS_ARABES_UNIDOS,
    RITREA, ESLOVAQUIA, ESLOVENIA, ESPANA, ESTADOS_UNIDOS, ESTONIA, ETIOPIA,
    ILIPINAS, FINLANDIA, FIYI, FRANCIA, GABON, GAMBIA, GEORGIA, GHANA, GRANADA,
    RECIA, GUATEMALA, GUYANA, GUINEA, GUINEA_ECUATORIAL, GUINEA_BISAU, HAITI,
    HONDURAS, HUNGRIA, INDIA, INDONESIA, IRAK, IRAN, IRLANDA, ISLANDIA,
    ISLAS_MARSHALL, ISLAS_SALOMON, ISRAEL, ITALIA, JAMAICA, JAPON, JORDANIA,
    KAZAJISTAN, KENIA, KIRGUISTAN, KIRIBATI, KUWAIT, LAOS, LESOTO, LETONIA,
    LIBANO, LIBERIA, LIBIA, LIECHTENSTEIN, LITUANIA, LUXEMBURGO, MADAGASCAR,
    MALASIA, MALAUI, MALDIVAS, MALI, MALTA, MARRUECOS, MAURICIO, MAURITANIA,
    MEXICO, MICRONESIA, MOLDAVIA, MONACO, MONGOLIA, MONTENEGRO, MOZAMBIQUE,
    NAMIBIA, NAURU, NEPAL, NICARAGUA, NIGER, NIGERIA, NORUEGA, NUEVA_ZELANDA,
    OMAN, PAISES_BAJOS, PAKISTAN, PALAOS, PANAMA, PAPUA_NUEVA_GUINEA, PARAGUAY,
    PERU, POLONIA, PORTUGAL, REINO_UNIDO, REPUBLICA_CENTROAFRICANA,
    REPUBLICA_CHECA, REPUBLICA_DE_MACEDONIA, REPUBLICA_DEL_CONGO,
    REPUBLICA_DEMOCRATICA_DEL_CONGO, REPUBLICA_DOMINICANA, REPUBLICA_SUDAFRICANA,
    RUANDA, RUMANIA, RUSIA, SAMOA, SAN_CRISTOBAL_Y_NIEVES, SAN_MARINO,
    AN_VICENTE_Y_LAS_GRANADINAS, SANTA_LUCIA, SANTO_TOME_Y_PRINCIPE, SENEGAL,
    ERBIA, SEYCHELLES, SIERRA_LEONA, SINGAPUR, SIRIA, SOMALIA, SRI_LANKA,
    UAZILANDIA, SUDAN, SUDAN_DEL_SUR, SUECIA, SUIZA, SURINAM, TAILANDIA, TANZANIA,
    AYIKISTAN, TIMOR_ORIENTAL, TOGO, TONGA, TRINIDAD_Y_TOBAGO, TUNEZ, TURKMENISTAN,
    URQUIA, TUVALU, UCRANIA, UGANDA, URUGUAY, UZBEKISTAN, VANUATU, VENEZUELA,
    IETNAM, YEMEN, YIBUTI, ZAMBIA, ZIMBABUE,
}
