/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author Jean
 */
public interface Chile {
    
    
    enum REGIONES implements Chile{
    TARAPACA, ANTOFAGASTA, ATACAMA, COQUIMBO, VALPARAISO, LIBERTADOR_GENERAL_BERNARDO_OHIGGINS,
    MAULE, BIO_BIO, LA_ARAUCANIA, LOS_LAGOS, AYSEN_DEL_GENERAL_CARLOS_IBANEZ_DEL_CAMPO,
    MAGALLANES_Y_ANTARTICA, REGION_METROPOLITANA, LOS_RIOS, ARICA_Y_PARINACOTA, ÑUBLE;
    }
    
    enum TARAPACA implements Chile{
        ALTO_HOSPICIO, IQUIQUE, CAMIÑA, COLCHANE, HUARA, PICA, POZO_ALMONTE;
    }
    enum ANTOFAGASTA implements Chile{
        ANTOFAGASTA, MEJILLONES, SIERRA_GORDA, TALTAL, CALAMA, OLLAGÜE, 
        SAN_PEDRO_DE_ATACAMA, MARÍA_ELENA, TOCOPILLA;
    }
    enum ATACAMA implements Chile{
        CHAÑARAL, DIEGO_DE_ALMAGRO, CALDERA, COPIAPÓ, TIERRA_AMARILLA, 
        ALTO_DEL_CARMEN, FREIRINA, HUASCO, VALLENAR;
    }
    enum COQUIMBO implements Chile{
        CANELA, ILLAPEL, LOS_VILOS, SALAMANCA, ANDACOLLO, COQUIMBO, LA_HIGUERA,
        LA_SERENA, PAIHUANO, VICUÑA, COMBARBALÁ, MONTE_PATRIA, OVALLE,_PUNITAQUI,
        RÍO_HURTADO;
    }
    enum VALPARAISO implements Chile{
        ISLA_DE_PASCUA, CALLE_LARGA, LOS_ANDES, RINCONADA_DE_LOS_ANDES, SAN_ESTEBAN,
        LIMACHE, OLMUÉ, QUILPUÉ, VILLA_ALEMANA, CABILDO, LA_LIGUA, PAPUDO, PETORCA,
        ZAPALLAR, HIJUELAS, LA_CALERA, LA_CRUZ, NOGALES, QUILLOTA, ALGARROBO, CARTAGENA,
        EL_QUISCO, EL_TABO, SAN_ANTONIO, SANTO_DOMINGO, CATEMU, LLAILLAY, PANQUEHUE,
        PUTAENDO, SAN_FELIPE, SANTA_MARÍA, CASABLANCA, CONCÓN, JUAN_FERNÁNDEZ, PUCHUNCAVÍ,
        QUINTERO, VALPARAÍSO, VIÑA_DEL_MAR;
    }
    enum LIBERTADOR_GENERAL_BERNARDO_OHIGGINS implements Chile{
        CODEGUA, COÍNCO, COLTAUCO, DOÑIHUE, GRANEROS, LAS_CABRAS, MACHALÍ, MALLOA, 
        OLIVAR, PEUMO, PICHIDEGUA, QUINTA_DE_TILCOCO, RANCAGUA, REQUÍNOA, RENGO, 
        SAN_FRANCISCO_DE_MOSTAZAL, SAN_VICENTE_DE_TAGUA_TAGUA, LA_ESTRELLA, LITUECHE, 
        MARCHIGÜE, NAVIDAD, PAREDONES, PICHILEMU, CHÉPICA, CHIMBARONGO, LOLOL, NANCAGUA, 
        PALMILLA, PERALILLO, PLACILLA, PUMANQUE, SAN_FERNANDO, SANTA_CRUZ;
    }
    enum MAULE implements Chile{
        CAUQUENES, CHANCO, PELLUHUE, CURICÓ, HUALAÑÉ, LICANTÉN, MOLINA, RAUCO, ROMERAL,
        SAGRADA_FAMILIA, TENO, VICHUQUÉN, COLBÚN, LINARES, LONGAVÍ, PARRAL, RETIRO,
        SAN_JAVIER_DE_LONCOMILLA, VILLA_ALEGRE, YERBAS_BUENAS, CONSTITUCIÓN, CUREPTO,
        EMPEDRADO, MAULE, PELARCO, PENCAHUE, RÍO_CLARO, SAN_CLEMENTE, SAN_RAFAEL, TALCA;
    }
    enum BIO_BIO implements Chile{
        ARAUCO, CAÑETE, CONTULMO, CURANILAHUE, LEBU, LOS_ÁLAMOS, TIRÚA, ALTO_BIOBÍO, 
        ANTUCO, CABRERO, LAJA, LOS_ÁNGELES, MULCHÉN, NACIMIENTO, NEGRETE, QUILACO, 
        QUILLECO, SAN_ROSENDO, SANTA_BÁRBARA, TUCAPEL, YUMBEL, CHIGUAYANTE, CONCEPCIÓN, 
        CORONEL, FLORIDA, HUALPÉN, HUALQUI, LOTA, PENCO, SAN_PEDRO_DE_LA_PAZ, SANTA_JUANA, 
        TALCAHUANO, TOMÉ;
    }
    enum LA_ARAUCANIA implements Chile{
        CARAHUE, CHOLCHOL, CUNCO, CURARREHUE, FREIRE, GALVARINO, GORBEA, LAUTARO, 
        LONCOCHE, MELIPEUCO, NUEVA_IMPERIAL, PADRE_LAS_CASAS, PERQUENCO, PITRUFQUÉN,
        PUCÓN, SAAVEDRA, TEMUCO, TEODORO_SCHMIDT, TOLTÉN, VILCÚN, VILLARRICA, ANGOL,
        COLLIPULLI, CURACAUTÍN, ERCILLA, LONQUIMAY, LOS_SAUCES, LUMACO, PURÉN, RENAICO,
        TRAIGUÉN, VICTORIA;
    }
    enum LOS_LAGOS implements Chile{
      ANCUD, CASTRO, CHONCHI, CURACO_DE_VÉLEZ, DALCAHUE, PUQUELDÓN, QUEILÉN, QUELLÓN, 
      QUEMCHI, QUINCHAO, CALBUCO, COCHAMÓ, FRESIA, FRUTILLAR, LLANQUIHUE, LOS_MUERMOS, 
      MAULLÍN, PUERTO_MONTT, PUERTO_VARAS, OSORNO, PUERTO_OCTAY, PURRANQUE, PUYEHUE,
      RÍO_NEGRO, SAN_PABLO, SAN_JUAN_DE_LA_COSTA, CHAITÉN, FUTALEUFÚ , HUALAIHUÉ, PALENA;
    }    
    enum AYSEN_DEL_GENERAL_CARLOS_IBANEZ_DEL_CAMPO implements Chile{
        AYSÉN, CISNES, GUAITECAS, COCHRANE, OHIGGINS, TORTEL, COYHAIQUE, 
        LAGO_VERDE, CHILE_CHICO, RÍO_IBÁÑEZ;
    }
    enum MAGALLANES_Y_ANTARTICA implements Chile{
        ANTÁRTICA, CABO_DE_HORNOS, LAGUNA_BLANCA, PUNTA_ARENAS, RÍO_VERDE, SAN_GREGORIO, 
        PORVENIR, PRIMAVERA, TIMAUKEL, NATALES, TORRES_DEL_PAINE;
    }
    enum REGION_METROPOLITANA implements Chile{
       COLINA, LAMPA, TILTIL, PIRQUE, PUENTE_ALTO, SAN_JOSÉ_DE_MAIPO, BUIN, CALERA_DE_TANGO,
       PAINE, SAN_BERNARDO, ALHUÉ, CURACAVÍ, MARÍA_PINTO, MELIPILLA, SAN_PEDRO, CERRILLOS, 
       CERRO_NAVIA, CONCHALÍ, EL_BOSQUE, ESTACIÓN_CENTRAL, HUECHURABA, INDEPENDENCIA, 
       LA_CISTERNA, LA_GRANJA, LA_FLORIDA, LA_PINTANA, LA_REINA, LAS_CONDES, LO_BARNECHEA, 
       LO_ESPEJO, LO_PRADO, MACUL, MAIPÚ, ÑUÑOA, PEDRO_AGUIRRE_CERDA, PEÑALOLÉN, PROVIDENCIA, 
       PUDAHUEL, QUILICURA, QUINTA_NORMAL, RECOLETA, RENCA, SAN_MIGUEL, SAN_JOAQUÍN, SAN_RAMÓN,
       SANTIAGO, VITACURA, EL_MONTE, ISLA_DE_MAIPO, PADRE_HURTADO, PEÑAFLOR, TALAGANTE;
    }
    enum LOS_RIOS implements Chile{
        FUTRONO, LA_UNIÓN, LAGO_RANCO, RÍO_BUENO, CORRAL, LANCO, LOS_LAGOS, MÁFIL,
        MARIQUINA, PAILLACO, PANGUIPULLI, VALDIVIA;
    }
    enum ARICA_Y_PARINACOTA implements Chile{
        ARICA,CAMARONES,GENERAL_LAGOS,PUTRE;
    }
    enum ÑUBLE implements Chile{
        BULNES, CHILLÁN, CHILLÁN_VIEJO, EL_CARMEN, PEMUCO, PINTO, QUILLÓN, SAN_IGNACIO, 
        YUNGAY, COBQUECURA, COELEMU, NINHUE, PORTEZUELO, QUIRIHUE, RÁNQUIL, TREGUACO, 
        COIHUECO, ÑIQUÉN, SAN_CARLOS, SAN_FABIÁN, SAN_NICOLÁS;
    }
}